### ISSUE TITLE
"Connection" and "Host" headers not checked

### ISSUE THREAD

**Issue by Anzey** [warmcat/libwebsockets#1423]
"Connection" and "Host" headers are not validated during handshake (checked with v2.4-stable).
According https://tools.ietf.org/html/rfc6455:
"4.2.1.  Reading the Client's Opening Handshake
...
   The client's opening handshake consists of the following parts.  If
   the server, while reading the handshake, finds that the client did
   not send a handshake that matches the description below (note that as
   per [RFC2616], the order of the header fields is not important),
   including but not limited to any violations of the ABNF grammar
   specified for the components of the handshake, the server MUST stop
   processing the client's handshake and return an HTTP response with an
   appropriate error code (such as 400 Bad Request).
...
   2.   A |Host| header field containing the server's authority.
...
   4.   A |Connection| header field that includes the token "Upgrade",
        treated as an ASCII case-insensitive value."

**Comment by lws-team** [comment]
Would you like to propose a patch to solve this to your liking?

**Comment by Anzey** [comment]
First I have found this...:
			while (n < sizeof(protocol_name) - 1 &&
			       *p && *p != ',') {
				/* ignore leading spaces */
				if (!non_space_char_found && *p == ' ') {
					**n++;**
					continue;
				}
				non_space_char_found = 1;
				protocol_name[n++] = *p++;
			}

**Comment by lws-team** [comment]
I pushed a fix changing that to `p++` on v2.4-stable, v3.0-stable and master.

**Comment by Anzey** [comment]
Great, but above is not solution to the original problem. It is merely small bug in tokenizer used to parse header. Attached is my proposal to check "connection: upgrade" header. Generally the problem here is lack of "real" tokenizer for the headers parsing (e.g. horizontal tabs - see https://greenbytes.de/tech/webdav/rfc7230.html#header.fields%3E).
"Host" header is still not checked and it seems to be more tricky.
[connection_header.txt](https://github.com/warmcat/libwebsockets/files/2455819/connection_header.txt)

**Comment by lws-team** [comment]
I think what you say about the lack of some nicer way to process string tokens is indeed the bigger problem.

I added an api for doing this on master, and patches to convert the exist ws protocol parsing and for h1 (it doesn't exist on h2) check for upgrade on the "connection" header using the new api, along with a selftest added for it in CI.

About host header, this is actually used if no SNI... if SNI is working, it actually selects the vhost the connection binds to without Host:.  If no SNI, then Host: is used to choose by comparing it with vhost names.

I'm not really sure what checking it means since the client can send what it wants... I guess in browser context it has some meaning.

I saw you are on v2.4, is it possible for you to save the effort of backporting this to 2.4 and use master solution for this stuff?

**Comment by Anzey** [comment]
Attached is my patch for v2.4.
Changes/fixes:
- separators in tokenizer according to https://greenbytes.de/tech/webdav/rfc7230.html#rule.token.separators,
- "connection: upgrade" check fixed,
- explicit check for "host" header added (in h1 case only).
[tokenizer.txt](https://github.com/warmcat/libwebsockets/files/2463931/tokenizer.txt)

**Comment by lws-team** [comment]
Nice job... it's pushed on v2.4-stable unchanged.

IIUI I should also take from this

 - connection: must exist check

 - host also must at least exist check

is that all that should come back from this to master?

**Comment by Anzey** [comment]
Please also check separators set.

**Comment by Anzey** [comment]
Note that tokenizer's test shall be updated if separator list changed.

**Comment by lws-team** [comment]
On master I added a flag `LWS_TOKENIZE_F_RFC7230_DELIMS` that lets you allow anything not in that delimiter set or a control character etc into a token.  Otherwise by default only A-Z, a-z, 0-9, _ and any valid utf-8 is allowed in a token, everything else not a control character, partial utf-8 etc is a delimiter.  Since it's not an official api on v2.4, I think what you have already is enough there.

I also added utf-8 validation and test cases on master as well...

 - The patch checking for upgrade in Connection now also fails missing connection hdr on h1.

 - If it's a h1 ws upgrade, it requires the presence of Host:

AFAIK that should be it... thanks for the help.

**Comment by lws-team** [comment]
> However it still seems that i get a handshake even though i input incorrect values in both Host and Connection fields, it even works when the string is empty.

I pushed a patch on v2.4-stable aligning the code with what's on master... does that help?

**Comment by Blondiejohan** [comment]
On the matter of the connection it seems to have solved the problem, i no longer receive a handshake when i input an incorrect Connection string or do not send a connection variable at all.
However i still receive a handshake when i input an incorrect Host variable.
Thank you for your fast response!

**Comment by lws-team** [comment]
As it stands, it's not trying to confirm what's in host, just that there's something.

Actually the connection is routed to the select vhost by either SNI matching the vhost name, or already by matching the Host: header to the vhost name if no TLS.  If you're using TLS, the client will also confirm that the address in the cert like "warmcat.com" or whatever matches the desired host.

**Comment by Blondiejohan** [comment]
The bug i'm working on is regarding the Section 4.1  RFC-6455: The request MUST contain a |Host| header field whose value contains /host/ plus optionally ":" followed by /port/ (when not using the default port).

The tester that have sent me this bug is insisting that the server rejects the handshake if the host header field doesn't contain this:  "A |Host| header field containing the server's authority."

**Comment by lws-team** [comment]
Just simply checking this against the logical vhost name will break a lot of casual use-cases where nobody took care to align the vhost name with the host name.  And often those use-cases treat, eg, localhost and 127.0.0.1 as interchangeable.  Other cases may have aliases like www.myserver.com and myserver.com which they treat as interchangable CNAMEs... this'll break that.

I think this has no real security value, since if the user controls the client he can put what he wants there... it seems to be for browsers with the idea they can't be easily redirected to the wrong place with js.   TLS should stop that anyway.

It can be done, but it seems it should be done by a flag on the vhost to say it really wants to check the Host: field against the vhost name.

**Comment by Blondiejohan** [comment]
In our project we do not currently run TLS, so we don't get the benefit of host in header checking that way. 
I agree that it shouldn't be put as a default state but since the RFC-6455 dictates that it must be done to follow the protocol correctly i think it would be a good feature to be able to enable with a flag as you said.
Is this something that would be easily implemented from your side or is it something we should put in locally as a patch?

**Comment by lws-team** [comment]
I pushed a patch on master that implements a vhost options flag for this.  minimal-ws-server shows
how to use it, it's enabled with the -h flag there.

**Comment by lws-team** [comment]
It won't get backported by me for a couple of reasons... v2.4 is too old and this patch changes the public api by adding the options flag.  That would mean bumping the v2.4 soname, then there are two kinds of .so and public api for one version... it doesn't make any sense.  Old versions may get internal fixes, but no new features.

You can either backport it yourself (a reminder this is LGPL'd and you will have to provide your changes with the binary) or use master.  Master will soon become v3.1.
