### ISSUE TITLE
proxy setting for websocket

### ISSUE THREAD

**Issue by bluenred9** [warmcat/libwebsockets#1704]
I'm making a client that connects to a websocket server.
Sending and receiving messages works fine.

However, if lws_set_proxy is called to support proxy or http_proxy_address of lws_context_creation_info is set, the connection is not established.

20 seconds after printing "Proxy read EAGAIN ... retrying".

How do I support proxy when making a websocket connection?

**Comment by lws-team** [comment]
So... how can I reproduce this?

**Comment by bluenred9** [comment]
I will upload the code that is reproduced.

**Comment by lws-team** [comment]
I think adding setting the proxy address in a minimal example is half the problem.  But it would be good if I didn't have to set up and maintain a proxy... I don't actually use this stuff myself.

**Comment by bluenred9** [comment]
The main code is shown below.

`
static int
callback_client(struct lws *wsi, enum lws_callback_reasons reason,
    void *user, void *in, size_t len);

static struct lws_protocols protocols[] = {
    { 
        "push_protocol", 
        callback_client, 
        sizeof(struct per_session_data), 
        1024, 
        0, NULL, 0 
    },
    { NULL, NULL, 0, 0 } /* terminator */
};

static struct lws_context *context;

static struct lws_protocol_vhost_options pvo_interrupted = {
    NULL,
    NULL,
    "interrupted",		/* pvo name */
    NULL	/* pvo value */
};

static struct lws_protocol_vhost_options pvo_path = {
	&pvo_interrupted,
	NULL,
	"path",		/* pvo name */
	NULL	/* pvo value */
};

static struct lws_protocol_vhost_options pvo_proxy_type = {
	&pvo_path,
	NULL,
	"proxy_type",		/* pvo name */
	NULL	/* pvo value */
};

static struct lws_protocol_vhost_options pvo_proxy_uri = {
	&pvo_proxy_type,
	NULL,
	"proxy_uri",		/* pvo name */
	NULL	/* pvo value */
};


static const struct lws_protocol_vhost_options pvo = {
    NULL,		/* "next" pvo linked-list */
    &pvo_proxy_uri,	/* "child" pvo linked-list */
    "push_protocol",	/* protocol name we belong to on this vhost */
    ""		/* ignored */
};

static const struct lws_extension extensions[] = {
    {
        "permessage-deflate",
        lws_extension_callback_pm_deflate,
        "permessage-deflate"
        "; client_no_context_takeover"
    "; client_max_window_bits"
    },
    { NULL, NULL, NULL /* terminator */ }
};

static int
connect_client(struct lws *wsi)
{

	struct vhost_data *vhd = (struct vhost_data *)lws_protocol_vh_priv_get(lws_get_vhost(wsi), lws_get_protocol(wsi));

    struct lws_client_connect_info i;

    memset(&i, 0, sizeof(i));

    i.context = vhd->context;

    i.port = 80;
    i.address = "push.test.bdrive.com";
    i.path = *vhd->path;
    i.host = i.address;
    i.origin = i.address;
    //i.ssl_connection = LCCSCF_USE_SSL;
    
    i.vhost = vhd->vhost;

    i.pwsi = &vhd->client_wsi;

    lwsl_user("connecting to %s:%d/%s\n", i.address, i.port, i.path);

    return !lws_client_connect_via_info(&i);
}

static void
__minimal_destroy_message(void *_msg)
{
    struct msg *msg = (struct msg*)_msg;

    free(msg->payload);
    msg->payload = NULL;
    msg->len = 0;
}

static void
schedule_callback(struct lws *wsi, int reason, int secs)
{
    lws_timed_callback_vh_protocol(lws_get_vhost(wsi),
        lws_get_protocol(wsi), reason, secs);
}

int _lws_protocol_init(struct lws *wsi, void *in)
{
	const struct lws_protocols *p = lws_get_protocol(wsi);
	struct vhost_data *vhd = (struct vhost_data*)lws_protocol_vh_priv_zalloc(lws_get_vhost(wsi), p, sizeof(struct vhost_data));
	if (!vhd)
		return -1;

	vhd->context = lws_get_context(wsi);
	vhd->vhost = lws_get_vhost(wsi);

	/* get the pointer to "interrupted" we were passed in pvo */
	vhd->interrupted = (int *)lws_pvo_search(
		(const struct lws_protocol_vhost_options *)in,
		"interrupted")->value;

	vhd->path = (const char **)lws_pvo_search(
		(const struct lws_protocol_vhost_options *)in,
		"path")->value;
    
	vhd->proxy_type = (int *)lws_pvo_search(
		(const struct lws_protocol_vhost_options *)in,
		"proxy_type")->value;

	vhd->proxy_url = (const char **)lws_pvo_search(
		(const struct lws_protocol_vhost_options *)in,
		"proxy_uri")->value;
    
    /*
	if (*vhd->proxy_type == PROXY_HTTP)
	{
		const char *uri = *vhd->proxy_url;
		int ret = lws_set_proxy(lws_get_vhost(wsi), *vhd->proxy_url);
		ret = ret + 1;
	}
	else if (*vhd->proxy_type == PROXY_SOCK5)
	{
		lws_set_socks(lws_get_vhost(wsi), *vhd->proxy_url);
	}
    */

	if (connect_client(wsi))
		schedule_callback(wsi, LWS_CALLBACK_USER, 1);

	if (p && p->user)
	{
		Push *push = (Push*)p->user;
		push->SetLWS(wsi);
	}

	return 0;
}

int _lws_client_established(struct per_session_data *pss, const struct lws_protocols *p)
{
	lwsl_user("LWS_CALLBACK_CLIENT_ESTABLISHED\n");

	pss->ring = lws_ring_create(sizeof(struct msg), RING_DEPTH, __minimal_destroy_message);
	if (!pss->ring)
		return 1;

	pss->tail = 0;

	if (p && p->user)
	{
		Push *push = (Push*)p->user;
		push->SetSessionData(pss);
		push->cb_->Connected();
	}

	return 0;
}

int _lws_client_writable(struct lws *wsi, struct per_session_data *pss)
{
	lwsl_user("LWS_CALLBACK_CLIENT_WRITEABLE\n");

	if (pss->write_consume_pending)
	{
		/* perform the deferred fifo consume */
		lws_ring_consume_single_tail(pss->ring, &pss->tail, 1);
		pss->write_consume_pending = 0;
	}

	const struct msg *pmsg = (const msg *)lws_ring_get_element(pss->ring, &pss->tail);
	if (pmsg == nullptr) 
	{
		lwsl_user(" (nothing in ring)\n");
		return 0;
	}

	int flags = lws_write_ws_flags( pmsg->binary ? LWS_WRITE_BINARY : LWS_WRITE_TEXT, 
									pmsg->first, pmsg->final);

	/* notice we allowed for LWS_PRE in the payload already */
	int m = lws_write(wsi, ((unsigned char *)pmsg->payload) + LWS_PRE, pmsg->len, (enum lws_write_protocol)LWS_WRITE_TEXT);
	if (m < (int)pmsg->len)
	{
		lwsl_err("ERROR %d writing to ws socket\n", m);
		return -1;
	}

	lwsl_user(" wrote %d: flags: 0x%x first: %d final %d\n", m, flags, pmsg->first, pmsg->final);

	if (pmsg && pmsg->final)
		pss->completed = 1;

	/*
	* Workaround deferred deflate in pmd extension by only
	* consuming the fifo entry when we are certain it has been
	* fully deflated at the next WRITABLE callback.  You only need
	* this if you're using pmd.
	*/
	pss->write_consume_pending = 1;
	lws_callback_on_writable(wsi);

	if (pss->flow_controlled &&
		(int)lws_ring_get_count_free_elements(pss->ring) > RING_DEPTH - 5) 
	{
		lws_rx_flow_control(wsi, 1);
		pss->flow_controlled = 0;
	}

	return 0;
}

int _lws_client_receive(struct lws *wsi, struct per_session_data *pss, void *in, size_t len)
{
	lwsl_user("LWS_CALLBACK_CLIENT_RECEIVE: %4d (rpp %5d, first %d, last %d, bin %d)\n",
		(int)len, (int)lws_remaining_packet_payload(wsi),
		lws_is_first_fragment(wsi),
		lws_is_final_fragment(wsi),
		lws_frame_is_binary(wsi));

	const struct lws_protocols *p = lws_get_protocol(wsi);

	if (p && p->user)
	{
		Push *push = (Push*)p->user;
		string msg((char*)in, len);

		push->cb_->MessageReceived(msg.c_str());
	}

	return 0;
}

int _lws_client_con_error(struct lws *wsi, void *in)
{
	lwsl_err("CLIENT_CONNECTION_ERROR: %s\n", in ? (char *)in : "(null)");

	const struct lws_protocols *p = lws_get_protocol(wsi);
	Push *push = nullptr;
	if (p && p->user)
		push = (Push*)p->user;

	struct vhost_data *vhd = (struct vhost_data *)lws_protocol_vh_priv_get(lws_get_vhost(wsi), lws_get_protocol(wsi));

	vhd->client_wsi = NULL;

	if (!*vhd->interrupted)
		*vhd->interrupted = 3;
	lws_cancel_service(lws_get_context(wsi));

	if( push )
		push->cb_->Disconnected();

	return 0;
}

int _lws_client_con_closed(struct lws *wsi, struct per_session_data *pss)
{
	lwsl_user("LWS_CALLBACK_CLIENT_CLOSED\n");

	const struct lws_protocols *p = lws_get_protocol(wsi);
	Push *push = nullptr;
	if (p && p->user)
		push = (Push*)p->user;

	struct vhost_data *vhd = (struct vhost_data *)lws_protocol_vh_priv_get(lws_get_vhost(wsi), lws_get_protocol(wsi));

    if (pss)
    {
        lws_ring_destroy(pss->ring);
        vhd->client_wsi = NULL;
        if (!*vhd->interrupted)
            *vhd->interrupted = 1 + pss->completed;
    }
    else
    {
        *vhd->interrupted = 1;
    }


	lws_cancel_service(lws_get_context(wsi));
	

	if (push)
		push->cb_->Disconnected();

	return 0;
}


static int
callback_client(struct lws *wsi, enum lws_callback_reasons reason,
    void *user, void *in, size_t len)
{
    struct per_session_data *pss = (struct per_session_data *)user;

    switch (reason) 
	{
    case LWS_CALLBACK_WSI_CREATE:
        //this_thread::sleep_for(chrono::seconds(1));
        break;
    case LWS_CALLBACK_PROTOCOL_INIT:
		return _lws_protocol_init(wsi, in);

    case LWS_CALLBACK_CLIENT_ESTABLISHED:
		return _lws_client_established(pss, lws_get_protocol(wsi));

	case LWS_CALLBACK_CLIENT_WRITEABLE:
		return _lws_client_writable(wsi, pss);

    case LWS_CALLBACK_CLIENT_RECEIVE:
		return _lws_client_receive(wsi, pss, in, len);

    case LWS_CALLBACK_CLIENT_CONNECTION_ERROR:
		return _lws_client_con_error(wsi, in);

    case LWS_CALLBACK_CLIENT_CLOSED:
		return _lws_client_con_closed(wsi, pss);

        /* rate-limited client connect retries */

    case LWS_CALLBACK_USER:
        lwsl_notice("%s: LWS_CALLBACK_USER\n", __func__);
        if (connect_client(wsi))
            schedule_callback(wsi, LWS_CALLBACK_USER, 1);
        break;
    case LWS_CALLBACK_WSI_DESTROY:
        return _lws_client_con_closed(wsi, pss);

    default:
        break;
    }

    return 0;
}

void Push::SetSessionData(struct per_session_data* pss)
{
    pss_ = pss;
}

void Push::SetLWS(struct lws *wsi)
{
	wsi_ = wsi;
}

AERROR Push::Connect(IPushCallback * cb, int _proxy_type, const char *_proxy_uri)
{
	GLOGNOFLA(LM_PUSH, LOGLEVEL::LL_DEBUG, "Connect to push server");
    cb_ = cb;
	proxy_type_ = _proxy_type;
	if (_proxy_uri)
		proxy_uri_ = _proxy_uri;

    thread_ = new thread([this]()
    {
        int n, logs = LLL_USER | LLL_ERR | LLL_WARN | LLL_NOTICE 
            | LLL_INFO  | LLL_PARSER  | LLL_HEADER | LLL_EXT | LLL_CLIENT | LLL_LATENCY 
             | LLL_DEBUG ;
        lws_set_log_level(logs, NULL);

        //url
		int path_len = strlen(cb_->GetToken()) + 2;
		char *url_path = (char*)malloc(path_len);
		memset(url_path, 0, path_len);
		sprintf(url_path, "/%s", cb_->GetToken());
		
		protocols->user = this;

		struct lws_context_creation_info info;
        struct lws_context *context;

		memset(&info, 0, sizeof info); 
        
		info.port = CONTEXT_PORT_NO_LISTEN;
        info.protocols = protocols;
        info.extensions = extensions;

		interrupted_ = 0;
		pvo_interrupted.value = (const char *)&interrupted_;
		pvo_path.value = (const char*)&url_path;

		info.pvo = &pvo;

        info.pt_serv_buf_size = 32 * 1024;

        info.options = LWS_SERVER_OPTION_DO_SSL_GLOBAL_INIT | LWS_SERVER_OPTION_VALIDATE_UTF8;
        //info.options = 0;
        info.gid = -1;
        info.uid = -1;

        info.fd_limit_per_thread = 1 + 1 + 1;

		info.http_proxy_address = "proxy_host:port";
		info.http_proxy_port = port;

        info.mounts;

        context = lws_create_context(&info);
        if (!context) {
            lwsl_err("lws init failed\n");
            return AERROR::FAILED;
        }

		while (!lws_service(context, 0) && !interrupted_);

        lws_context_destroy(context);
		if (url_path)
			free(url_path);
		
		GLOGNOFLA(LM_PUSH, LOGLEVEL::LL_DEBUG, "push loop finished.");

    });

    return AERROR::SUCCESS;
}`

**Comment by lws-team** [comment]
I pushed some patches on v3.1-stable, v3.2-stable and master after testing http_proxy on squid... master had some breakage due to the async dns resolver work.  Please give the updated trees a try.

**Comment by lws-team** [comment]
Well, this works here on all the versions now, if any problem please update the issue.

**Comment by vinifr** [comment]
Hello. I am able to connect to the server via HTTPs proxy, apparently. 

[2023/04/02 19:19:01:9028] N: http_proxy: __lws_lc_tag:  ++ [wsicli|0|WS/h1/http_proxy/ws.iqoption.com] (1)
[2023/04/02 19:19:01:9029] N: [wsicli|0|WS/h1/http_proxy/ws.iqoption.com]: lws_client_connect_3_connect: trying 70.72.164.75 (Proxy IP)

But the server is still seeing my original IP, not the proxy IP, 70.72.164.75. Does lws require some parameter to the server receiving the proxy IP?

**Comment by lws-team** [comment]
Is there some reason you're not setting http_proxy environment var?  Eg

$ http_proxy=myproxy.com:3128  myapp

**Comment by vinifr** [comment]
Running as a client, captive_portal_detect is required for HTTPs proxy connection?

**Comment by rsenn** [comment]
take care with C++, your std::string proxy/proxy_host are temporaries, only
valid within websocket_init(), and lws_create_context() won't make copies
of any strings in the lws_context_creation_info struct. you would probably
need to strdup() them, and free() them again when the lws_context is
destroyed.
