### ISSUE TITLE
Crashes during Codenomicon testing

### ISSUE THREAD

**Issue by aatukora** [warmcat/libwebsockets#391]
This may not be the most useful bug report at the moment, but I'll try getting other information that might be useful here.  When running the Codenomicon test suite against our product, we've noticed a couple of crashes in libwebsocket.

I've tried debugging this, but haven't made much progress.  There might be multiple crashes here.

* Original backtrace I was working with was (this was using libwebsockets 1.5):
#0  0x00007fb6fd8e45c9 in raise () from /lib64/libc.so.6
#1  0x00007fb6fd8e5cd8 in abort () from /lib64/libc.so.6
#2  0x00007fb6fd924db7 in __libc_message () from /lib64/libc.so.6
#3  0x00007fb6fd92c19d in _int_free () from /lib64/libc.so.6
#4  0x0000000000cda733 in _realloc ()
#5  0x0000000000cd8da2 in lws_free_header_table ()
#6  0x0000000000cdf4d4 in lws_handshake_server ()
#7  0x0000000000ce11ac in libwebsocket_read ()
#8  0x0000000000cdf7b3 in lws_server_socket_service ()
#9  0x0000000000cd7996 in libwebsocket_service_fd ()
#10 0x0000000000cde530 in lws_plat_service ()
#11 0x0000000000c76a39 in websocket_server_thread (context=<optimized out>) at [path]/websocket_server.cpp:429
#12 0x00007fb6fdc77df3 in start_thread () from /lib64/libpthread.so.0
#13 0x00007fb6fd9a51ad in clone () from /lib64/libc.so.6

* I upgraded to libwebsockets 1.6 and tried the tests again, and it crashed with (when running in gdb):
#0  0x0000000001035687 in lws_parse ()
#1  0x000000000103b43a in lws_handshake_server ()
#2  0x000000000103d255 in lws_read ()
#3  0x000000000103bc53 in lws_server_socket_service ()
#4  0x0000000001033d06 in lws_service_fd ()
#5  0x000000000103a778 in lws_plat_service ()
#6  0x0000000000fe19f9 in websocket_server_thread (context=[optimised out]) at [path]/websocket_server.cpp:427
#7  0x00007ffff61b5e9a in start_thread (arg=0x7fffa5d90700) at pthread_create.c:308
#8  0x00007ffff5ee338d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:112
#9  0x0000000000000000 in ?? ()

* I tried running in valgrind, and it crashed with:
==7726== Invalid write of size 1
==7726==    at 0x1036279: lws_rx_sm (in [application])
==7726==    by 0x103BF3F: lws_interpret_incoming_packet (in [application])
==7726==    by 0x103D397: lws_read (in [application])
==7726==    by 0x1033DDA: lws_service_fd (in [application])
==7726==    by 0x103A777: lws_plat_service (in [application])
==7726==    by 0xFE19F8: websocket_server_thread(void*) (websocket_server.cpp:427)
==7726==    by 0x6848E99: start_thread (pthread_create.c:308)
==7726==    by 0x6B5138C: clone (clone.S:112)
==7726==  Address 0x41633dd0 is not stack'd, malloc'd or (recently) free'd
==7726==
==7726==
==7726== Process terminating with default action of signal 11 (SIGSEGV)
==7726==  Access not within mapped region at address 0x41633DD0
==7726==    at 0x1036279: lws_rx_sm (in [application])
==7726==    by 0x103BF3F: lws_interpret_incoming_packet (in [application])
==7726==    by 0x103D397: lws_read (in [application])
==7726==    by 0x1033DDA: lws_service_fd (in [application])
==7726==    by 0x103A777: lws_plat_service (in [application])
==7726==    by 0xFE19F8: websocket_server_thread(void*) (websocket_server.cpp:427)
==7726==    by 0x6848E99: start_thread (pthread_create.c:308)
==7726==    by 0x6B5138C: clone (clone.S:112)
==7726==  If you believe this happened as a result of a stack
==7726==  overflow in your program's main thread (unlikely but
==7726==  possible), you can try to increase the size of the
==7726==  main thread stack using the --main-stacksize= flag.
==7726==  The main thread stack size used in this run was 8388608.

I think this last crash is due to out-of-bounds array access at parsers.c:860

		if (wsi->u.ws.all_zero_nonce)
			wsi->u.ws.rx_user_buffer[LWS_SEND_BUFFER_PRE_PADDING +
			       (wsi->u.ws.rx_user_buffer_head++)] = c;

but I couldn't work out where 'rx_user_buffer_head' was getting corrupted.

What other information would be useful here? I can try and get a packet capture of the traffic around the time of the crash (but we currently use secure websockets, so I'll probably have to change that first).

**Comment by lws-team** [comment]
Well what you are testing is lws + your user code, and it being C your user code is able to write things in lws internal structs and corrupt them.  Or it could be a library bug, although it'd be surprising.  So the first move would be try to test with the test-server or test-client and see if it's reproducible there.

You're also using threads, lws is not threadsafe in the traditional sense, although it is safe to fire writeable callbacks at live wsis from other threads, if your other thread tried to operate on a dead wsi you would get these symtoms.

**Comment by lws-team** [comment]
Did you get any hints about this?

**Comment by aatukora** [comment]
Sorry for the delay. I'm going to try running against the test-server today.

**Comment by lws-team** [comment]
Great... I am highly curious if there's something to fix.

**Comment by aatukora** [comment]
Yup, managed to crash the test-server with what looks the same as the third crash in my original report:

Program received signal SIGSEGV, Segmentation fault.
0x0000000000408e29 in lws_rx_sm ()
(gdb) bt
#0  0x0000000000408e29 in lws_rx_sm ()
#1  0x000000000040f440 in lws_interpret_incoming_packet ()
#2  0x0000000000410bd8 in lws_read ()
#3  0x0000000000406c37 in lws_service_fd ()
#4  0x000000000040dc40 in lws_plat_service ()
#5  0x0000000000404631 in main ()

Unfortunately it wasn't compiled with -g, so gdb didn't have debugging information (I'll attach what I have anyway).

[gdb_output.txt](https://github.com/warmcat/libwebsockets/files/87410/gdb_output.txt)

Running it again now, but nothing interesting has happened so far.

**Comment by lws-team** [comment]
To trace the problem we need the line of source that blows chunks, and ideally the last few things the fuzzer sent.

**Comment by lws-team** [comment]
Hum I stared at it and pushed a patch that should solve the third one.  Please try it

https://github.com/warmcat/libwebsockets/commit/9928cccdb6571149340984c0d1cbc264ad82398a

**Comment by aatukora** [comment]
Thanks! I'll give it a go.

**Comment by aatukora** [comment]
Ok, so admittedly I picked up a lot more than just that changeset when I grabbed https://github.com/warmcat/libwebsockets/archive/master.zip, but it now crashes (well, asserts) quite quickly:

lwsts[8158]: Unable to open '/nu/aatukora/edonus/libs/libwebsockets/build/test.html'
    get  = /
    host: = 10.209.86.109:0:0:
    connection: = Upgrade
    origin: = wss://10.209.86.109:33432
    http/1.1  = HTTP/1.1
    sec-websocket-key: = dGhlIHNhbXBsZSBub25jZQ==
    sec-websocket-version: = 13
lwsts[8158]: test_server_fops_open: opening /nu/aatukora/edonus/libs/libwebsockets/build/test.html, ret -1, len 0
lwsts[8158]: Unable to open '/nu/aatukora/edonus/libs/libwebsockets/build/test.html'
libwebsockets-test-server: /nu/aatukora/edonus/libs/libwebsockets/lib/parsers.c:118: lws_free_header_table: Assertion `wsi->u.hdr.ah' failed.

Program received signal SIGABRT, Aborted.
0x00007ffff6fe50d5 in __GI_raise (sig=<optimised out>) at ../nptl/sysdeps/unix/sysv/linux/raise.c:64
64      ../nptl/sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) bt
#0  0x00007ffff6fe50d5 in __GI_raise (sig=<optimised out>) at ../nptl/sysdeps/unix/sysv/linux/raise.c:64
#1  0x00007ffff6fe883b in __GI_abort () at abort.c:91
#2  0x00007ffff6fddd9e in __assert_fail_base (fmt=<optimised out>, assertion=0x41b738 "wsi->u.hdr.ah", file=0x41b690 "/nu/aatukora/edonus/libs/libwebsockets/lib/parsers.c", line=<optimised out>, function=<optimised out>) at assert.c:94
#3  0x00007ffff6fdde42 in __GI___assert_fail (assertion=0x41b738 "wsi->u.hdr.ah", file=0x41b690 "/nu/aatukora/edonus/libs/libwebsockets/lib/parsers.c", line=118, function=0x41bc60 "lws_free_header_table") at assert.c:103
#4  0x000000000040aace in lws_free_header_table (wsi=0x65bc60) at /nu/aatukora/edonus/libs/libwebsockets/lib/parsers.c:118
#5  0x0000000000416765 in lws_handshake_server (wsi=0x65bc60, buf=0x7fffffffdc50, len=0) at /nu/aatukora/edonus/libs/libwebsockets/lib/server.c:565
#6  0x0000000000419854 in lws_read (wsi=0x65bc60, buf=0x6241c7 "\n\r\n\n\r\n\n\r\n\n\r\n\n\r\n\n\r\n\n\r\n\n\r\n\n\r\n\n\r\n\n\r\n\n\r\n\n\r\n\n\r\n\n\r\n\n\r\n\n\r\n\n\r\n\n\r\n\n\r\n\n\r\n\n\r\n\n\r\n\n\r\n\n\r\n\n\r\n\n\r\n\n\r\n\n\r\n\n\r\n\n\r\n\n\r\n\n\r\n\n\r\n\n\r\n\n\r\n\n\r\n\n\r\n\n\r\n\n\r\n\n\r\n\n\r\n\n\r\n\n\r\n\n\r\n\n\r\n\n\r\n\n\r\n\n\r\n\n\r\n\n\r\n\n\r\n\n\r\n\n\r\n\n\r\n\n\r\n\n\r\n\n\r\n\n\r\n\n\r\n\n\r\n\n\r\n\n\r\n\n\r\n\n\r\n\n\r\n\n\r"..., len=271) at /nu/aatukora/edonus/libs/libwebsockets/lib/handshake.c:109
#7  0x0000000000416b5b in lws_server_socket_service (context=0x624010, wsi=0x65bc60, pollfd=0x626e40) at /nu/aatukora/edonus/libs/libwebsockets/lib/server.c:722
#8  0x0000000000408745 in lws_service_fd (context=0x624010, pollfd=0x626e40) at /nu/aatukora/edonus/libs/libwebsockets/lib/service.c:508
#9  0x0000000000414ebf in lws_plat_service (context=0x624010, timeout_ms=50) at /nu/aatukora/edonus/libs/libwebsockets/lib/lws-plat-unix.c:206
#10 0x0000000000408c46 in lws_service (context=0x624010, timeout_ms=50) at /nu/aatukora/edonus/libs/libwebsockets/lib/service.c:761
#11 0x00000000004049b5 in main (argc=6, argv=0x7fffffffea08) at /nu/aatukora/edonus/libs/libwebsockets/test-server/test-server.c:374
(gdb)
#0  0x00007ffff6fe50d5 in __GI_raise (sig=<optimised out>) at ../nptl/sysdeps/unix/sysv/linux/raise.c:64
#1  0x00007ffff6fe883b in __GI_abort () at abort.c:91
#2  0x00007ffff6fddd9e in __assert_fail_base (fmt=<optimised out>, assertion=0x41b738 "wsi->u.hdr.ah", file=0x41b690 "/nu/aatukora/edonus/libs/libwebsockets/lib/parsers.c", line=<optimised out>, function=<optimised out>) at assert.c:94
#3  0x00007ffff6fdde42 in __GI___assert_fail (assertion=0x41b738 "wsi->u.hdr.ah", file=0x41b690 "/nu/aatukora/edonus/libs/libwebsockets/lib/parsers.c", line=118, function=0x41bc60 "lws_free_header_table") at assert.c:103
#4  0x000000000040aace in lws_free_header_table (wsi=0x65bc60) at /nu/aatukora/edonus/libs/libwebsockets/lib/parsers.c:118
#5  0x0000000000416765 in lws_handshake_server (wsi=0x65bc60, buf=0x7fffffffdc50, len=0) at /nu/aatukora/edonus/libs/libwebsockets/lib/server.c:565
#6  0x0000000000419854 in lws_read (wsi=0x65bc60, buf=0x6241c7 "\n\r\n\n\r\n\n\r\n\n\r\n\n\r\n\n\r\n\n\r\n\n\r\n\n\r\n\n\r\n\n\r\n\n\r\n\n\r\n\n\r\n\n\r\n\n\r\n\n\r\n\n\r\n\n\r\n\n\r\n\n\r\n\n\r\n\n\r\n\n\r\n\n\r\n\n\r\n\n\r\n\n\r\n\n\r\n\n\r\n\n\r\n\n\r\n\n\r\n\n\r\n\n\r\n\n\r\n\n\r\n\n\r\n\n\r\n\n\r\n\n\r\n\n\r\n\n\r\n\n\r\n\n\r\n\n\r\n\n\r\n\n\r\n\n\r\n\n\r\n\n\r\n\n\r\n\n\r\n\n\r\n\n\r\n\n\r\n\n\r\n\n\r\n\n\r\n\n\r\n\n\r\n\n\r\n\n\r\n\n\r\n\n\r\n\n\r\n\n\r"..., len=271) at /nu/aatukora/edonus/libs/libwebsockets/lib/handshake.c:109
#7  0x0000000000416b5b in lws_server_socket_service (context=0x624010, wsi=0x65bc60, pollfd=0x626e40) at /nu/aatukora/edonus/libs/libwebsockets/lib/server.c:722
#8  0x0000000000408745 in lws_service_fd (context=0x624010, pollfd=0x626e40) at /nu/aatukora/edonus/libs/libwebsockets/lib/service.c:508
#9  0x0000000000414ebf in lws_plat_service (context=0x624010, timeout_ms=50) at /nu/aatukora/edonus/libs/libwebsockets/lib/lws-plat-unix.c:206
#10 0x0000000000408c46 in lws_service (context=0x624010, timeout_ms=50) at /nu/aatukora/edonus/libs/libwebsockets/lib/service.c:761
#11 0x00000000004049b5 in main (argc=6, argv=0x7fffffffea08) at /nu/aatukora/edonus/libs/libwebsockets/test-server/test-server.c:374

**Comment by lws-team** [comment]
I think I found it and pushed a fix

https://github.com/warmcat/libwebsockets/commit/83080734640aceec79d46c01be7fde7c70a6a01c

That one only hurts because the assert is there, without it the case is actually handled ok since on free, the allocation ptr is NULLed.  But I wanted to find all paths that tried to do it twice and eliminate them...which it did...

**Comment by lws-team** [comment]
If the second, lws_parse() one is still coming, or any other ones, the line number should help a lot.

**Comment by aatukora** [comment]
Thanks Andy!  Here's the next one:

#0  0x00007ffff702e592 in _int_malloc (av=0x7ffff7366720, bytes=600) at malloc.c:3670
#1  0x00007ffff7030f85 in __GI___libc_malloc (bytes=600) at malloc.c:2924
#2  0x00007ffff7020c3d in __GI_open_memstream (bufloc=0x7fffffffd6e0, sizeloc=0x7fffffffd6f0) at memstream.c:79
#3  0x00007ffff709dd5b in __GI___vsyslog_chk (pri=28, flag=-1, fmt=0x41d8eb "%s", ap=0x7fffffffd748) at ../misc/syslog.c:169
#4  0x00007ffff709e3af in __syslog (pri=<optimised out>, fmt=<optimised out>) at ../misc/syslog.c:119
#5  0x0000000000414a55 in lwsl_emit_syslog (level=2, line=0x7fffffffd870 "Missing URI in HTTP request\n") at /nu/aatukora/edonus/libs/libwebsockets/lib/lws-plat-unix.c:95
#6  0x00000000004077f5 in _lws_logv (filter=2, format=0x41dae7 "Missing URI in HTTP request\n", vl=0x7fffffffd9a8) at /nu/aatukora/edonus/libs/libwebsockets/lib/libwebsockets.c:854
#7  0x00000000004078b1 in _lws_log (filter=2, format=0x41dae7 "Missing URI in HTTP request\n") at /nu/aatukora/edonus/libs/libwebsockets/lib/libwebsockets.c:862
#8  0x0000000000415c4e in lws_http_action (wsi=0x878f00) at /nu/aatukora/edonus/libs/libwebsockets/lib/server.c:206
#9  0x00000000004161bc in lws_handshake_server (wsi=0x878f00, buf=0x7fffffffdc50, len=46) at /nu/aatukora/edonus/libs/libwebsockets/lib/server.c:358
#10 0x0000000000419848 in lws_read (wsi=0x878f00, buf=0x6241c9 "", len=319) at /nu/aatukora/edonus/libs/libwebsockets/lib/handshake.c:109
#11 0x0000000000416b5b in lws_server_socket_service (context=0x624010, wsi=0x878f00, pollfd=0x626e40) at /nu/aatukora/edonus/libs/libwebsockets/lib/server.c:722
#12 0x0000000000408745 in lws_service_fd (context=0x624010, pollfd=0x626e40) at /nu/aatukora/edonus/libs/libwebsockets/lib/service.c:508
#13 0x0000000000414ebf in lws_plat_service (context=0x624010, timeout_ms=50) at /nu/aatukora/edonus/libs/libwebsockets/lib/lws-plat-unix.c:206
#14 0x0000000000408c46 in lws_service (context=0x624010, timeout_ms=50) at /nu/aatukora/edonus/libs/libwebsockets/lib/service.c:761
#15 0x00000000004049b5 in main (argc=6, argv=0x7fffffffea08) at /nu/aatukora/edonus/libs/libwebsockets/test-server/test-server.c:374

**Comment by aatukora** [comment]
And this one.  Though this may be an OpenSSL bug:

#0  0x00007ffff702e592 in _int_malloc (av=0x7ffff7366720, bytes=320) at malloc.c:3670
#1  0x00007ffff7030f85 in __GI___libc_malloc (bytes=320) at malloc.c:2924
#2  0x00007ffff75eb134 in CRYPTO_malloc () from /lib/x86_64-linux-gnu/libcrypto.so.1.0.0
#3  0x00007ffff75f9c97 in ?? () from /lib/x86_64-linux-gnu/libcrypto.so.1.0.0
#4  0x00007ffff75f9dc5 in ?? () from /lib/x86_64-linux-gnu/libcrypto.so.1.0.0
#5  0x00007ffff76859ff in EVP_PKEY_CTX_dup () from /lib/x86_64-linux-gnu/libcrypto.so.1.0.0
#6  0x00007ffff76787dc in EVP_MD_CTX_copy_ex () from /lib/x86_64-linux-gnu/libcrypto.so.1.0.0
#7  0x00007ffff7990f86 in ?? () from /lib/x86_64-linux-gnu/libssl.so.1.0.0
#8  0x00007ffff798718e in ?? () from /lib/x86_64-linux-gnu/libssl.so.1.0.0
#9  0x00007ffff7984460 in ?? () from /lib/x86_64-linux-gnu/libssl.so.1.0.0
#10 0x0000000000412d4b in lws_ssl_capable_read (wsi=0x693180, buf=0x6240b8 "s3pPLMBiTxaQ9kYGzzhZRbK+xOo=", len=4096) at /nu/aatukora/edonus/libs/libwebsockets/lib/ssl.c:460
#11 0x0000000000408a04 in lws_service_fd (context=0x624010, pollfd=0x626e40) at /nu/aatukora/edonus/libs/libwebsockets/lib/service.c:613
#12 0x0000000000414ebf in lws_plat_service (context=0x624010, timeout_ms=50) at /nu/aatukora/edonus/libs/libwebsockets/lib/lws-plat-unix.c:206
#13 0x0000000000408c46 in lws_service (context=0x624010, timeout_ms=50) at /nu/aatukora/edonus/libs/libwebsockets/lib/service.c:761
#14 0x00000000004049b5 in main (argc=6, argv=0x7fffffffea08) at /nu/aatukora/edonus/libs/libwebsockets/test-server/test-server.c:374

**Comment by lws-team** [comment]
sorry what's up with the first of those, he's just logging a string with no vsprintf args.  It's malloc exhaustion?

**Comment by lws-team** [comment]
Again the second is also just malloc... what made it a problem?

**Comment by aatukora** [comment]
gdb makes it look like a segfault though? Possibly memory corruption?

The test has hit three of those crashes so far (two of the first, and the second on once).  I restarted the test-server each time and let it continue running.  It's been running fine for about an hour since crash now :)

**Comment by lws-team** [comment]
Hum... It's just allocating 600 bytes at that code itself.  Maybe there's a heap corruption that can only be felt afterwards at that time.  At your libc malloc, I am pretty sure there's nothing to fix.

If so it might help to sic valgrind on it.

**Comment by aatukora** [comment]
Apart from the three segfaults I've already mentioned, the suite ran to completion with no other crashes (193249 test cases in 17850585ms).

I started off another run with the test-server running in valgrind, and got this (for my ref, on test case 1335):
[valgrind_output.txt](https://github.com/warmcat/libwebsockets/files/89036/valgrind_output.txt)

I think this is the same as the first _int_malloc "crash" I reported above.

But it looks like my original crashes are fixed now :)

**Comment by lws-team** [comment]
I studied it and came up with this

https://github.com/warmcat/libwebsockets/commit/0e8403ec2849d7cb2a6cd6132d4821043ac2f98a

but this solves something on client, it's not directly your problem.

The info from valgrind is good, but it's not where the actual problem is coming from, so it's difficult to figure out what happened when it's not known what the fuzzer was feeding it when it blew.

**Comment by lws-team** [comment]
If you have the test case index, can you maybe repeat that test case and capture what it sent using tcpdump or whatever so I can reproduce it?

**Comment by aatukora** [comment]
I had to use non-secure websockets to get a packet capture that we could examine:
[fuzzing_traffic.pcap.txt](https://github.com/warmcat/libwebsockets/files/90339/fuzzing_traffic.pcap.txt) -- added .txt to make it accept the file

Program received signal SIGSEGV, Segmentation fault.
0x000000000040b2ad in issue_char (wsi=0x647f00, c=85 'U') at /nu/aatukora/edonus/libs/libwebsockets/lib/parsers.c:329
329                     wsi->u.hdr.ah->data[wsi->u.hdr.ah->pos++] = c;
(gdb)
(gdb) bt
#0  0x000000000040b2ad in issue_char (wsi=0x647f00, c=85 'U') at /nu/aatukora/edonus/libs/libwebsockets/lib/parsers.c:329
#1  0x000000000040bb88 in lws_parse (wsi=0x647f00, c=85 'U') at /nu/aatukora/edonus/libs/libwebsockets/lib/parsers.c:557
#2  0x000000000041608c in lws_handshake_server (wsi=0x647f00, buf=0x7fffffffdc60, len=107) at /nu/aatukora/edonus/libs/libwebsockets/lib/server.c:330
#3  0x0000000000419848 in lws_read (wsi=0x647f00, buf=0x62418b "pgrade\r\nSec-WebSocket-Accept: s3pPLMBiTxaQ9kYGzzhZRbK+xOo=\r\n\r\n", len=318) at /nu/aatukora/edonus/libs/libwebsockets/lib/handshake.c:109
#4  0x0000000000416b5b in lws_server_socket_service (context=0x624010, wsi=0x647f00, pollfd=0x626e40) at /nu/aatukora/edonus/libs/libwebsockets/lib/server.c:722
#5  0x0000000000408745 in lws_service_fd (context=0x624010, pollfd=0x626e40) at /nu/aatukora/edonus/libs/libwebsockets/lib/service.c:508
#6  0x0000000000414ebf in lws_plat_service (context=0x624010, timeout_ms=50) at /nu/aatukora/edonus/libs/libwebsockets/lib/lws-plat-unix.c:206
#7  0x0000000000408c46 in lws_service (context=0x624010, timeout_ms=50) at /nu/aatukora/edonus/libs/libwebsockets/lib/service.c:761
#8  0x00000000004049b5 in main (argc=5, argv=0x7fffffffea18) at /nu/aatukora/edonus/libs/libwebsockets/test-server/test-server.c:374

wsi->u.hdr.ah->data appears to be NULL.

(gdb) print wsi->u.hdr.ah->pos
$5 = 0
(gdb) print wsi->u.hdr.ah->data
$6 = 0x0
(gdb)
$7 = 0x0

**Comment by lws-team** [comment]
Thanks... the traffic dump isn't useful... it needs to be like tcpdump ... -s0 -X to get the packet payloads.  Which will make a monster file I am not sure it's feasible to replay... anyway let me try to understand how we can get there with NULL ah->data by using the "staring at the code" technique.

**Comment by aatukora** [comment]
Ah ok. I'll try that again

**Comment by aatukora** [comment]
[fuzzing_traffic-X.pcap.txt](https://github.com/warmcat/libwebsockets/files/90512/fuzzing_traffic-X.pcap.txt)
It's not that big.. hope this is somewhat useful.

**Comment by lws-team** [comment]
Thanks... looking through it I feel a lot better about the things we're already immune to!

I'll try to reproduce them from the bottom up.

**Comment by JoakimSoderberg** [comment]
`git push coverity_scan` might help with some of this? If you have not let coverity scan the code lately

**Comment by lws-team** [comment]
They're different beasts... both useful... I scanned v1.6 release a few weeks ago, we are at zero defects.

The fuzzer really aggressively takes a crap on assumptions the static analyzer can't reach and - this is what has bitten us here - actually goes and tries your error paths in a way that normal operation doesn't.

I started writing a fuzzer proxy for lws a few days ago that will sit between the client and server and semi-randomly take a whiz on what's passing through, bloat it out, snip bits and meddle bits in place.  I'm not sure it'll be the same as the commercial fuzzer but evidently it'll be way better than nothing.

**Comment by lws-team** [comment]
Alright on a long plane ride back home I did and just pushed the start of the 'fuzxy' fuzzing proxy.  He works (just do http_proxy=localhost:8880 before running the test client), but he just does one fuzzing operation held in the code to start with.

And unfortunately that one isn't the one that causes this symptom.  However we now have a convenient basis to build on for mangling stuff in one or both directions, which I will continue with shortly.

**Comment by lws-team** [comment]
I just ran us against coverity again, I introduced some new small problems with the new code (1 unused return code, 2 dereference context or wsi before NULL check... but the wsi can never be NULL and context only if context create failed; 2 in fuzxy socket error handling) but these are fixed now and too trivial to be related to this problem.

I'll start looking at the other fuzzing activities in the tcpdump log and try them in fuzxy next.

**Comment by lws-team** [comment]
I tried injecting 64K of various scary junk in various headers and the method, path etc, I found some problems with timeout code that I introduced today (and some that preexisted) and fixed them.  Bet despite running everything with valgrind otherwise I can't upset it.

Just as a sanity check in case it was releated to the old timeout problem can you check that current HEAD still dies on this test for you?

**Comment by aatukora** [comment]
Yup, I'll give it a go

**Comment by aatukora** [comment]
Still crashes in the same way:

Program received signal SIGSEGV, Segmentation fault.
0x000000000040ba77 in issue_char (wsi=0x64a5e0, c=85 'U') at /nu/aatukora/edonus/libs/libwebsockets/lib/parsers.c:329
329                     wsi->u.hdr.ah->data[wsi->u.hdr.ah->pos++] = c;
(gdb) bt
#0  0x000000000040ba77 in issue_char (wsi=0x64a5e0, c=85 'U') at /nu/aatukora/edonus/libs/libwebsockets/lib/parsers.c:329
#1  0x000000000040c352 in lws_parse (wsi=0x64a5e0, c=85 'U') at /nu/aatukora/edonus/libs/libwebsockets/lib/parsers.c:557
#2  0x00000000004172b7 in lws_handshake_server (wsi=0x64a5e0, buf=0x7fffffffdbf0, len=107) at /nu/aatukora/edonus/libs/libwebsockets/lib/server.c:330
#3  0x000000000041ac60 in lws_read (wsi=0x64a5e0, buf=0x626a53 "pgrade\r\nSec-WebSocket-Accept: s3pPLMBiTxaQ9kYGzzhZRbK+xOo=\r\n\r\n", len=318) at /nu/aatukora/edonus/libs/libwebsockets/lib/handshake.c:109
#4  0x0000000000417e54 in lws_server_socket_service (context=0x626010, wsi=0x64a5e0, pollfd=0x628e40) at /nu/aatukora/edonus/libs/libwebsockets/lib/server.c:738
#5  0x0000000000408d6c in lws_service_fd_tsi (context=0x626010, pollfd=0x628e40, tsi=0) at /nu/aatukora/edonus/libs/libwebsockets/lib/service.c:508
#6  0x0000000000416008 in lws_plat_service_tsi (context=0x626010, timeout_ms=50, tsi=0) at /nu/aatukora/edonus/libs/libwebsockets/lib/lws-plat-unix.c:228
#7  0x0000000000416099 in lws_plat_service (context=0x626010, timeout_ms=50) at /nu/aatukora/edonus/libs/libwebsockets/lib/lws-plat-unix.c:242
#8  0x00000000004092a0 in lws_service (context=0x626010, timeout_ms=50) at /nu/aatukora/edonus/libs/libwebsockets/lib/service.c:768
#9  0x0000000000404b65 in main (argc=5, argv=0x7fffffffea18) at /nu/aatukora/edonus/libs/libwebsockets/test-server/test-server.c:374

Another (slightly longer) capture of the traffic: 
[fuzzing_traffic_3.pcap.txt](https://github.com/warmcat/libwebsockets/files/96297/fuzzing_traffic_3.pcap.txt)

Could internal data structures be getting into a bad state due to a certain pattern of traffic (as opposed to a single request)?  I can get a capture of all the traffic up to the point of the crash if that might help (though it may be big).

**Comment by aatukora** [comment]
This should be all the traffic from the start of a clean run: [fuzzing_traffic_4.pcap.txt](https://github.com/warmcat/libwebsockets/files/96325/fuzzing_traffic_4.pcap.txt)

**Comment by lws-team** [comment]
Thanks for all the detailed reports.  Basically it's hard to find because there is a chink in some very thick armour somewhere, this code is trying hard to be secure already with bytewise state machines and other defensive schemes.  So unless we hit it at exactly where the problem is, it won't fall over.

The other thing slowing us down is the fuzzer is proprietary so directly reproducing it isn't possible.

Anyway now I know it's still there I will continue.  The backtrace seems to tell us ah pos was allowed to get too big on one path, or there is other corruption.

**Comment by lws-team** [comment]
Just going by the backtrace I audited all uses of issue_char and found some problems.  Please retry with the patch I just pushed.

**Comment by lws-team** [comment]
Sorry I repushed it, make sure it is bc4012916dd765754b094a92a0b8627edb05a558

**Comment by lws-team** [comment]
It'd be helpful if I can get another test to see whether that nailed that specific problem, and how many issues seem to be remaining.

**Comment by aatukora** [comment]
Sorry, I did run this in the morning, but forgot to comment!

It went again at the same point :(

#0  0x000000000040baa1 in issue_char (wsi=0x64a5e0, c=85 'U') at /nu/aatukora/edonus/libs/libwebsockets/lib/parsers.c:336
#1  0x000000000040c3e8 in lws_parse (wsi=0x64a5e0, c=85 'U') at /nu/aatukora/edonus/libs/libwebsockets/lib/parsers.c:574
#2  0x00000000004172bb in lws_handshake_server (wsi=0x64a5e0, buf=0x7fffffffdbf0, len=107) at /nu/aatukora/edonus/libs/libwebsockets/lib/server.c:330
#3  0x000000000041ac64 in lws_read (wsi=0x64a5e0, buf=0x626a53 "pgrade\r\nSec-WebSocket-Accept: s3pPLMBiTxaQ9kYGzzhZRbK+xOo=\r\n\r\n", len=318) at /nu/aatukora/edonus/libs/libwebsockets/lib/handshake.c:109
#4  0x0000000000417e58 in lws_server_socket_service (context=0x626010, wsi=0x64a5e0, pollfd=0x628e40) at /nu/aatukora/edonus/libs/libwebsockets/lib/server.c:738
#5  0x0000000000408d78 in lws_service_fd_tsi (context=0x626010, pollfd=0x628e40, tsi=0) at /nu/aatukora/edonus/libs/libwebsockets/lib/service.c:508
#6  0x000000000041600c in lws_plat_service_tsi (context=0x626010, timeout_ms=50, tsi=0) at /nu/aatukora/edonus/libs/libwebsockets/lib/lws-plat-unix.c:228
#7  0x000000000041609d in lws_plat_service (context=0x626010, timeout_ms=50) at /nu/aatukora/edonus/libs/libwebsockets/lib/lws-plat-unix.c:242
#8  0x00000000004092ac in lws_service (context=0x626010, timeout_ms=50) at /nu/aatukora/edonus/libs/libwebsockets/lib/service.c:768
#9  0x0000000000404b65 in main (argc=5, argv=0x7fffffffea18) at /nu/aatukora/edonus/libs/libwebsockets/test-server/test-server.c:374

**Comment by lws-team** [comment]
Thanks... then I'll redouble my efforts to try understand how that's possible.

**Comment by lws-team** [comment]
Studying the tcpdump, he makes a big series of improperly terminated HTTP upgrades and at some point in that we stop.  So I will try to duplicate that.

**Comment by lws-team** [comment]
I found the reproducer while porting suspicious-looking fuzzer sections from the logs to fuzxy one by one...now looking for the actual bug...

**Comment by lws-team** [comment]
OK this time it should be solved, please retry with HEAD once more.  I'm also interested if any more failure modes are coming.

**Comment by aatukora** [comment]
This is looking good :+1:  The non-secure websocket tests against the test-server all passed (i.e. it didn't crash).  Running the secure suite now; will report back in ~3 hours.

**Comment by lws-team** [comment]
Great... although if the ssl version has any additional weakness we will have to instrument either the fuzzer or the library in order to see what it's doing, and that'll only help if it isn't breaking it at ssl layer (although I think Codenomicon already 'been there done that' wrt openssl).  After connection setup it's largely just a tunnel for lws, all the parsing etc is identical so I expect / hope nothing new.

**Comment by aatukora** [comment]
Yup, ssl version is fine too! Thanks a lot with all your help tracking this down :)

When do you think 1.7 will be released?

**Comment by lws-team** [comment]
Thanks a lot for helping with the debug process.

I would like to clear issue #404 somehow and in the meanwhile get the last changes (like multi service threads) more widely tested, otherwise it's in a good place for a new release as it is.  So 'soon' hopefully.

**Comment by aatukora** [comment]
Ok, great. Thanks again!

**Comment by lws-team** [comment]
Hi... current master HEAD is my planned v1.7 release... could you possibly give it a spin on the fuzzer?  There have been significant changes internally this week but they don't affect the network data processing code directly.  Hopefully he's still in good shape.

**Comment by aatukora** [comment]
Yup, I'll give it a go.

**Comment by aatukora** [comment]
All still passes :)

**Comment by lws-team** [comment]
Thanks a lot ^^
