### ISSUE TITLE
Errors in dot-dot handling in pathnames

### ISSUE THREAD

**Issue by dosvald** [warmcat/libwebsockets#481]
I was crafting some plain HTTP requests and I tried making a request to a non-absolute pathname. I noticed that libwebsockets does not do (totally) correct "../../" removal.

1. three or more dots in directory name are treated same as two dots
`GET /foo/dir/..../file` or `GET /foo/dir/.../file` -> `/foo/file` in `*in` at callback time  
I don't think three or more dots should be special really, like two dots are

2. when request target is not an absolute pathname (does not start with a slash), libwebsockets wrongly fixes up the path. For example, when I do `echo -e "GET http://other-server.local/../foo HTTP/1.1\r\n\r" | nc localhost` (like a proxy request), in debug output of libwebsockets I see `Method: GET request for 'http:foo'`, and the `*in` parameter is such in the callback. Making any other relative request with dot-dot element ends up in wrong pathname, such as `GET one/two/../abc` -> `oneabc`.

3. Two dots are kept at start of a relative pathname
`GET ../secret-file.txt` -> `../secret-file.txt` is in the `*in` pointer in callback. libwebsockets test server handles that, but maybe the library should do it?

For cases 2. and 3. according to[this answer](http://stackoverflow.com/questions/27638278/do-http-paths-have-to-start-with-a-slash) and [RFC](http://tools.ietf.org/html/rfc7230#section-5.3) request target which is not an absolute pathname is only used with proxying, and nowhere can the relative pathname be seen. This means that valid HTTP applications should not make such requests.

Also, of course the application can always check if there's a leading slash in the pathname and reject or add it if not. But maybe libwebsockets could do that,  With that in mind, I don't know what the correct behavior should be when a client requests a target which is not an absolute pathname. Maybe if such a case is detected, drop the connection automatically?

**Comment by lws-team** [comment]
The goal of the path and urldecoding processing is to guarantee ../../../%2e%2e/../etc/passwd type attacks will fail without the user code thinking about that.  If you look in ./test-server/attack.sh (test script for this) you will see what it does eliminate.

For 1), there's no real legit use for files or directories called '....'.  If you think it should accept it, patches welcome.

2) and 3) sound like as you say moving the test server leading / check into the library is needed, and return a 405 or so... I'll look at that thismorning.

**Comment by lws-team** [comment]
I pushed a patch on master + v1.7-stable that returns a 403 Forbidden if a URI is coming that doesn't start with a /.

**Comment by dosvald** [comment]
Hi,

Your commit does fix the leading slash problem.

I made a request to fix the more-than-two-dots handling, as well as a related issue that I noticed where it didn't handle `/folder/other/../file -> /folder/file` parsing correctly.

**Comment by dosvald** [comment]
I've found additional bugs while fixing that pull request.

Here's the list of problems with URI parsing that I can see.

1. Anything starting with two or more dots is handled like it was `..` (the item listed as 1. above)
Example: `/some/.../dir/file` goes to `/some/file` but, should be left as-is.

2. Two-dots doesn't correctly go to parent directory
Example: `GET /folder/other/.../dir/file` goes to `/folderdir/file` instead of `/folder/dir/file`

3. Inconsistent percent-encoding parsing - dots sometimes interact wrongly when non-hex chars follow `%`
Example: `GET /foo/.%xyz` goes to `GET /foo/%.xyz`

4. Percent-encoding at end doesn't behave same as in the middle when one hex char follows `%`
Example: `GET /1/%a/2` stays as-is, but `GET /1/2/%a` goes to `/1/2/`, i.e. loses that `%a` at the end

Problems 1 and 2 were targets of my pull request.
Problems 3 and 4 are still present...

**Comment by dosvald** [comment]
With the new pulls of my commits, I still see some problems with URI parsing. mostly related to URI param parsing and the `?` character.

1. When putting a request for `GET /path?a=b&c=d` i get `*in = /path` and  params copied via `lws_hdr_copy(..., WSI_TOKEN_HTTP_URI_ARGS)` gets `a=bc=d`. How should I access the individual params `a=b` and `c=d`?

2. With my patches the case of 'GET /path/..?` is not handled well, I made a regression where `/path/..` is kept in the request path.

Here are files with results of some generated requests with and without my patches to compare for regressions by the way...

[now.txt](https://github.com/warmcat/libwebsockets/files/206982/now.txt)
[reverted-e5e84fd.txt](https://github.com/warmcat/libwebsockets/files/206983/reverted.txt)
[reverted-both-my-patches.txt](https://github.com/warmcat/libwebsockets/files/206988/reverted-both-my-patches.txt)



Maybe a rewrite/rethink/redesign of that request parsing part from scratch would be more efficient, since I seem to be tripping up in the interactions between '?', '../', previously '%' and some other maybe unknown bugs...

**Comment by lws-team** [comment]
There are api variants for accessing the individual x=y args

```
LWS_VISIBLE LWS_EXTERN int LWS_WARN_UNUSED_RESULT
lws_hdr_fragment_length(struct lws *wsi, enum lws_token_indexes h, int frag_idx);

/*
 * copies only fragment frag_idx of a header.  Normally this is only useful
 * to parse URI arguments like ?x=1&y=2, token index WSI_TOKEN_HTTP_URI_ARGS
 * fragment 0 will contain "x=1" and fragment 1 "y=2"
 */
LWS_VISIBLE LWS_EXTERN int
lws_hdr_copy_fragment(struct lws *wsi, char *dest, int len,
		      enum lws_token_indexes h, int frag_idx);
```

The only sane way is to add every test case to attack.sh and be able to confirm they all still work.

At least after your second patch, all the variations in there today work ok.

I'll look at your examples from that pov in the morning.

**Comment by lws-team** [comment]
Looking at your lists of results, what it used to do without the latest patches seems pretty reasonable from the perspective of "I'm not going to let you get anywhere with your dots".

The questions all seem to be around what should it do about malformed or incomplete %, the closest ones to dangerous seem to be

/%a../	GET '/%a../'

but that still leaves the attacker with a junk %<whatever> not useful for going backwards.

However if we revert the last patches and simply reject malformed %<hex><hex> in the library with a 405, doesn't that solve it?

**Comment by lws-team** [comment]
I pushed a patch on master replacing the last two, I get these results

```
- "/..../" -> 406 "/..../"
- "/.../." -> 406 "/.../"
- "/...//" -> 406 "/.../"
- "/.../a" -> 406 "/.../a"
- "/.../w" -> 406 "/.../w"
- "/.../?" -> 406 "/.../"
- "/.../%" -> 403
- "/../.." -> 200 "/"
- "/.././" -> 200 "/"
- "/../.a" -> 415 "/.a"
- "/../.w" -> 415 "/.w"
- "/../.." -> 200 "/"
- "/../.%" -> 403
- "/..//." -> 200 "/"
- "/..///" -> 200 "/"
- "/..//a" -> 415 "/a"
- "/..//w" -> 415 "/w"
- "/..//?" -> 200 "/"
- "/..//%" -> 403
- "/../a." -> 415 "/a."
- "/../a/" -> 406 "/a/"
- "/../aa" -> 415 "/aa"
- "/../aw" -> 415 "/aw"
- "/../a?" -> 415 "/a"
- "/../a%" -> 403
- "/../w." -> 415 "/w."
- "/../w/" -> 406 "/w/"
- "/../wa" -> 415 "/wa"
- "/../ww" -> 415 "/ww"
- "/../w?" -> 415 "/w"
- "/../w%" -> 403
- "/../?." -> 200 "/"
- "/../?/" -> 200 "/"
- "/../?a" -> 200 "/"
- "/../?w" -> 200 "/"
- "/../??" -> 200 "/"
- "/../?%" -> 403
- "/../%." -> 403
- "/../%/" -> 403
- "/../%a" -> 403
- "/../%w" -> 403
- "/../%?" -> 403
- "/../%%" -> 403
- "/./..." -> 415 "/..."
- "/./../" -> 200 "/"
- "/./..a" -> 415 "/..a"
- "/./..w" -> 415 "/..w"
- "/./..?" -> 200 "/"
- "/./..%" -> 403
- "/.//.." -> 200 "/"
- "/.a../" -> 406 "/.a../"
- "/.a/.." -> 200 "/"
- "/.w../" -> 406 "/.w../"
- "/.w/.." -> 200 "/"
- "/.?../" -> 415 "/."
- "/../.." -> 200 "/"
- "/.%../" -> 403
- "/.%/.." -> 403
- "//...." -> 415 "/...."
- "//.../" -> 406 "/.../"
- "//...a" -> 415 "/...a"
- "//...w" -> 415 "/...w"
- "//...?" -> 415 "/..."
- "//...%" -> 403
- "//../." -> 200 "/"
- "//..//" -> 200 "/"
- "//../a" -> 415 "/a"
- "//../w" -> 415 "/w"
- "//../?" -> 200 "/"
- "//../%" -> 403
- "//..a." -> 415 "/..a."
- "//..a/" -> 406 "/..a/"
- "//..aa" -> 415 "/..aa"
- "//..aw" -> 415 "/..aw"
- "//..a?" -> 415 "/..a"
- "//..a%" -> 403
- "//..w." -> 415 "/..w."
- "//..w/" -> 406 "/..w/"
- "//..wa" -> 415 "/..wa"
- "//..ww" -> 415 "/..ww"
- "//..w?" -> 415 "/..w"
- "//..w%" -> 403
- "//..?." -> 200 "/"
- "//..?/" -> 200 "/"
- "//..?a" -> 415 "/a"
- "//..?w" -> 415 "/w"
- "//..??" -> 200 "/"
- "//..?%" -> 403
- "//..%." -> 403
- "//..%/" -> 403
- "//..%a" -> 403
- "//..%w" -> 403
- "//..%?" -> 403
- "//..%%" -> 403
- "//./.." -> 200 "/"
- "///..." -> 415 "/..."
- "///../" -> 200 "/"
- "///..a" -> 415 "/..a"
- "///..w" -> 415 "/..w"
- "///..?" -> 200 "/"
- "///..%" -> 403
- "////.." -> 200 "/"
- "//a../" -> 406 "/a../"
- "//a/.." -> 200 "/"
- "//w../" -> 406 "/w../"
- "//w/.." -> 200 "/"
- "//?../" -> 200 "/"
- "//?/.." -> 200 "/"
- "//%../" -> 403
- "//%/.." -> 403
- "/a.../" -> 406 "/a.../"
- "/a../." -> 406 "/a../"
- "/a..//" -> 406 "/a../"
- "/a../a" -> 406 "/a../a"
- "/a../w" -> 406 "/a../w"
- "/a../?" -> 406 "/a../"
- "/a../%" -> 403
- "/a./.." -> 200 "/"
- "/a/..." -> 406 "/a/..."
- "/a/../" -> 200 "/"
- "/a/..a" -> 406 "/a/..a"
- "/a/..w" -> 406 "/a/..w"
- "/a/..?" -> 200 "/"
- "/a/..%" -> 403
- "/a//.." -> 200 "/"
- "/aa../" -> 406 "/aa../"
- "/aa/.." -> 200 "/"
- "/aw../" -> 406 "/aw../"
- "/aw/.." -> 200 "/"
- "/a?../" -> 415 "/a"
- "/a?/.." -> 415 "/a"
- "/a%../" -> 403
- "/a%/.." -> 403
- "/w.../" -> 406 "/w.../"
- "/w../." -> 406 "/w../"
- "/w..//" -> 406 "/w../"
- "/w../a" -> 406 "/w../a"
- "/w../w" -> 406 "/w../w"
- "/w../?" -> 406 "/w../"
- "/w../%" -> 403
- "/w./.." -> 200 "/"
- "/w/..." -> 406 "/w/..."
- "/w/../" -> 200 "/"
- "/w/..a" -> 406 "/w/..a"
- "/w/..w" -> 406 "/w/..w"
- "/w/..?" -> 200 "/"
- "/w/..%" -> 403
- "/w//.." -> 200 "/"
- "/wa../" -> 406 "/wa../"
- "/wa/.." -> 200 "/"
- "/ww../" -> 406 "/ww../"
- "/ww/.." -> 200 "/"
- "/w?../" -> 415 "/w"
- "/w?/.." -> 415 "/w"
- "/w%../" -> 403
- "/w%/.." -> 403
- "/?.../" -> 200 "/"
- "/?../." -> 200 "/"
- "/?..//" -> 200 "/"
- "/?../a" -> 200 "/"
- "/?../w" -> 200 "/"
- "/?../?" -> 200 "/"
- "/?../%" -> 403
- "/?./.." -> 200 "/"
- "/?/..." -> 200 "/"
- "/?/../" -> 200 "/"
- "/?/..a" -> 200 "/"
- "/?/..w" -> 200 "/"
- "/?/..?" -> 200 "/"
- "/?/..%" -> 403
- "/?//.." -> 200 "/"
- "/?a../" -> 200 "/"
- "/?a/.." -> 200 "/"
- "/?w../" -> 200 "/"
- "/?w/.." -> 200 "/"
- "/??../" -> 200 "/"
- "/??/.." -> 200 "/"
- "/?%../" -> 403
- "/?%/.." -> 403
- "/%.../" -> 403
- "/%../." -> 403
- "/%..//" -> 403
- "/%../a" -> 403
- "/%../w" -> 403
- "/%../?" -> 403
- "/%../%" -> 403
- "/%./.." -> 403
- "/%/..." -> 403
- "/%/../" -> 403
- "/%/..a" -> 403
- "/%/..w" -> 403
- "/%/..?" -> 403
- "/%/..%" -> 403
- "/%//.." -> 403
- "/%a../" -> 403
- "/%a/.." -> 403
- "/%w../" -> 403
- "/%w/.." -> 403
- "/%?../" -> 403
- "/%?/.." -> 403
- "/%%../" -> 403
- "/%%/.." -> 403
```

403 = parser rejected it (eg, %<nonhex>)
406 = test server received it, refused it because he doesn't like directories
415 = test server received it, wanted to serve it but didn't know the mimetype
200 = test server served it (basically / url -> test.html)

To reproduce, run libwebsockets-test-server &

```
#!/bin/sh

rm -f /tmp/results

for i in \
/..../ \
/.../. \
/...// \
/.../a \
/.../w \
/.../? \
/.../% \
/../.. \
/.././ \
/../.a \
/../.w \
/../.. \
/../.% \
/..//. \
/../// \
/..//a \
/..//w \
/..//? \
/..//% \
/../a. \
/../a/ \
/../aa \
/../aw \
/../a? \
/../a% \
/../w. \
/../w/ \
/../wa \
/../ww \
/../w? \
/../w% \
/../?. \
/../?/ \
/../?a \
/../?w \
/../?? \
/../?% \
/../%. \
/../%/ \
/../%a \
/../%w \
/../%? \
/../%% \
/./... \
/./../ \
/./..a \
/./..w \
/./..? \
/./..% \
/.//.. \
/.a../ \
/.a/.. \
/.w../ \
/.w/.. \
/.?../ \
/../.. \
/.%../ \
/.%/.. \
//.... \
//.../ \
//...a \
//...w \
//...? \
//...% \
//../. \
//..// \
//../a \
//../w \
//../? \
//../% \
//..a. \
//..a/ \
//..aa \
//..aw \
//..a? \
//..a% \
//..w. \
//..w/ \
//..wa \
//..ww \
//..w? \
//..w% \
//..?. \
//..?/ \
//..?a \
//..?w \
//..?? \
//..?% \
//..%. \
//..%/ \
//..%a \
//..%w \
//..%? \
//..%% \
//./.. \
///... \
///../ \
///..a \
///..w \
///..? \
///..% \
////.. \
//a../ \
//a/.. \
//w../ \
//w/.. \
//?../ \
//?/.. \
//%../ \
//%/.. \
/a.../ \
/a../. \
/a..// \
/a../a \
/a../w \
/a../? \
/a../% \
/a./.. \
/a/... \
/a/../ \
/a/..a \
/a/..w \
/a/..? \
/a/..% \
/a//.. \
/aa../ \
/aa/.. \
/aw../ \
/aw/.. \
/a?../ \
/a?/.. \
/a%../ \
/a%/.. \
/w.../ \
/w../. \
/w..// \
/w../a \
/w../w \
/w../? \
/w../% \
/w./.. \
/w/... \
/w/../ \
/w/..a \
/w/..w \
/w/..? \
/w/..% \
/w//.. \
/wa../ \
/wa/.. \
/ww../ \
/ww/.. \
/w?../ \
/w?/.. \
/w%../ \
/w%/.. \
/?.../ \
/?../. \
/?..// \
/?../a \
/?../w \
/?../? \
/?../% \
/?./.. \
/?/... \
/?/../ \
/?/..a \
/?/..w \
/?/..? \
/?/..% \
/?//.. \
/?a../ \
/?a/.. \
/?w../ \
/?w/.. \
/??../ \
/??/.. \
/?%../ \
/?%/.. \
/%.../ \
/%../. \
/%..// \
/%../a \
/%../w \
/%../? \
/%../% \
/%./.. \
/%/... \
/%/../ \
/%/..a \
/%/..w \
/%/..? \
/%/..% \
/%//.. \
/%a../ \
/%a/.. \
/%w../ \
/%w/.. \
/%?../ \
/%?/.. \
/%%../ \
/%%/.. \
; do

R=`rm -f /tmp/lwscap ; echo -n -e "GET $i HTTP/1.0\r\n\r\n" | nc localhost 7681 2>/dev/null >/tmp/lwscap; head -n1 /tmp/lwscap| cut -d' ' -f2`

cat /tmp/lwscap | head -n1
echo ==== $R


if [ "$R" != "403" ]; then
	U=`sudo journalctl -n50 | grep lws_http_serve | tail -n 1 | cut -d':' -f5 | cut -d' ' -f2`
	echo "- \"$i\" -> $R \"$U\"" >>/tmp/results
else
	echo "- \"$i\" -> $R" >>/tmp/results
fi
done

cat /tmp/results
```

**Comment by dosvald** [comment]
This percent-encoding cleanup is great. Looking at the code and that results txt, as far as I see it now handles better that dot and percent interaction (since invalid percent encoding is rejected).

But, even with your latest patch, it doesn't handle correctly the case of `/a/w/../a` , or `/path/to/dir/../other/dir`, (not in the big list of requests, but I tried it). When backing up it doesn't handle the slash (no change since before, this was always problem, one of my commits tried to address that but tripped up on other stuff as you can see.


Going through the code for `/a/w/../a`, this happens:
0. it would issue `/a/w/`,
1. then get to the second dot of, set state of slashdotdot. 
2. then it sees slash and will back up. Before backing up, `pos` points after the slash. = space where to put next char.
  - Then it `pos--` and it now points to the slash after 'w' (before loop),
  - then it enters do-while, `pos--`, pos points at 'w'. Loop check passes,
  - inside loop `pos--` now pos points to slash. Loop exits.
Now the bug: state is set to SEEN_SLASH, new slash is swallowed, but we have deleted the slash (three times `pos--`), and what is issued is '/a'.

Finally we see character `a` and now we have `/aa` instead of `/a/a`.

So, something about that backing up must be changed:
One solution would be to not swallow slash after backing up, but issue it. However then it needs to separate '?' and '/' handling again.
Maybe the better solution is to not decrement `pos` to slash, but to one char after that, swallow slash or '?' and set state SEEN_SLASH.

Or something similar...

**Comment by lws-team** [comment]
Okay.  But the only truly critical thing is 'can you hack your way out of the vhost's base directory with it'.  The rest of it is just corner cases that give the wrong result inside the correct vhost url space; he could have given that result directly so no big problem.

I'll add the cases you mention to attack.sh and look at them tonight or tomorrow.

**Comment by lws-team** [comment]
I updated the patch with a fix, and attack.sh with tests for those two cases too.

**Comment by dosvald** [comment]
Thanks, looks okay now
