### ISSUE TITLE
error while make

### ISSUE THREAD

**Issue by sacOO7** [warmcat/libwebsockets#742]
I was trying to execute make command on build files and I got following error.

```
[  2%] Building C object CMakeFiles/websockets.dir/lib/base64-decode.c.o
[  4%] Building C object CMakeFiles/websockets.dir/lib/handshake.c.o
[  6%] Building C object CMakeFiles/websockets.dir/lib/libwebsockets.c.o
[  8%] Building C object CMakeFiles/websockets.dir/lib/service.c.o
[ 10%] Building C object CMakeFiles/websockets.dir/lib/pollfd.c.o
[ 12%] Building C object CMakeFiles/websockets.dir/lib/output.c.o
[ 14%] Building C object CMakeFiles/websockets.dir/lib/parsers.c.o
[ 17%] Building C object CMakeFiles/websockets.dir/lib/context.c.o
[ 19%] Building C object CMakeFiles/websockets.dir/lib/alloc.c.o
[ 21%] Building C object CMakeFiles/websockets.dir/lib/header.c.o
[ 23%] Building C object CMakeFiles/websockets.dir/lib/client.c.o
[ 25%] Building C object CMakeFiles/websockets.dir/lib/client-handshake.c.o
[ 27%] Building C object CMakeFiles/websockets.dir/lib/client-parser.c.o
[ 29%] Building C object CMakeFiles/websockets.dir/lib/ssl.c.o
[ 31%] Building C object CMakeFiles/websockets.dir/lib/ssl-server.c.o
[ 34%] Building C object CMakeFiles/websockets.dir/lib/ssl-client.c.o
[ 36%] Building C object CMakeFiles/websockets.dir/lib/sha-1.c.o
[ 38%] Building C object CMakeFiles/websockets.dir/lib/lws-plat-unix.c.o
[ 40%] Building C object CMakeFiles/websockets.dir/lib/server.c.o
[ 42%] Building C object CMakeFiles/websockets.dir/lib/server-handshake.c.o
[ 44%] Building C object CMakeFiles/websockets.dir/lib/extension.c.o
[ 46%] Building C object CMakeFiles/websockets.dir/lib/extension-permessage-deflate.c.o
[ 48%] Building C object CMakeFiles/websockets.dir/lib/ranges.c.o
Linking C static library lib/libwebsockets.a
[ 48%] Built target websockets
Scanning dependencies of target test-client
[ 51%] Building C object CMakeFiles/test-client.dir/test-server/test-client.c.o
Linking C executable bin/libwebsockets-test-client
lib/libwebsockets.a(ssl.c.o): In function `lws_ssl_destroy':
ssl.c:(.text+0x322): undefined reference to `ERR_remove_thread_state'
lib/libwebsockets.a(ssl.c.o): In function `lws_ssl_context_destroy':
ssl.c:(.text+0xbf7): undefined reference to `ERR_remove_thread_state'
collect2: error: ld returned 1 exit status
make[2]: *** [bin/libwebsockets-test-client] Error 1
make[1]: *** [CMakeFiles/test-client.dir/all] Error 2
make: *** [all] Error 2
```

Can you tell me why this error occured. I think stable version is not uploaded on ubuntu distro.

**Comment by lws-team** [comment]
What version is your libssl-devel or whatever it is called on ubuntu?

**Comment by sacOO7** [comment]
I dont know . I just know that I have openssl installed on my pc

**Comment by sacOO7** [comment]
I think I have libssl-dev with latest version

**Comment by sacOO7** [comment]
Is there any other way I can use this library without building it ?

**Comment by lws-team** [comment]
Try

```
 $ dpkg -l libssl-dev
```

**Comment by lws-team** [comment]
It's packaged for Ubuntu, but only v1.7 on stable Ubuntu

https://launchpad.net/ubuntu/+source/libwebsockets

**Comment by sacOO7** [comment]
Ok, is there any command available to install in ubuntu ? I tried sudo apt-get install libwebsockets,but its not working.

**Comment by sacOO7** [comment]
The current version of libssl-dev is 1.0.1f-1ubun

**Comment by lws-team** [comment]
The ubuntu package is called `libwebsockets7` according to the page I linked to.

**Comment by sacOO7** [comment]
It's still not working. Can you tell me why its showing me make error?

**Comment by lws-team** [comment]
"It's not working" is not very useful to hear.

What are we even talking about any more... apt-get?

What actually happens?

It's 22:30 where I am, I'll try to understand the make error tomorrow.

**Comment by lws-team** [comment]
Your error is complaining no `ERR_remove_thread_state`.

This https://www.openssl.org/docs/man1.0.2/crypto/ERR_remove_thread_state.html - docs for 1.0.2 - says it was introduced in 1.0.0

```
ERR_remove_state() is available in all versions of SSLeay and OpenSSL. It was deprecated in OpenSSL 1.0.0 when ERR_remove_thread_state was introduced and thread IDs were introduced to identify threads instead of 'unsigned long'.
```

but this https://www.openssl.org/docs/man1.0.1/crypto/ERR_remove_state.html - it's docs for 1.0.1 exactly - only has the old api.

So it seems this was only introduced in 1.0.2.

I pushed a patch on master branch correcting the openssl version numbers 2ecbcca55dea8ff3f4cfe97ca31d57caad7f30d2

**Comment by sacOO7** [comment]
Hey thanks for your help, but it is still showing me same error. Maybe we need some improvements to patch.

**Comment by lws-team** [comment]
Yeah.

a7bf178606233954d2bf7780ad4477e49de678c8

**Comment by sacOO7** [comment]
Finally worked thanks .
