### ISSUE TITLE
Support file larger than 4GB

### ISSUE THREAD

**Issue by WebsocketUser** [warmcat/libwebsockets#916]
Support file large than 4GB?

**Comment by WebsocketUser** [comment]
I download file with 1.32 GB. It works fine.
I download file with 5GB, always download 1GB and then stop. Why??

**Comment by lws-team** [comment]
What is your platform?

**Comment by WebsocketUser** [comment]
Client side : windows 7 64 bit
Server side: windows 10 64 bit

**Comment by lws-team** [comment]
The VFS stuff in lws is already OK for 64-bit file lengths (the underlying type is size_t), but some of the content-length processing uses unsigned long, which in windows is 32-bit even for the 64-bit compiler.  In gcc for x86_64 anyway, those are 64-bit already.

I pushed a couple of patches on master that should help, please give it a go.

**Comment by WebsocketUser** [comment]
Client side : windows 7 64 bit
Server side: windows 10 64 bit

Both testing program run as Win32.

There have two place have to modify.
atoll cannot find in windows define.
size_t is 32 bits when run as win32 program.

I update two places and try to upload 5 GB file.
Server side use lws_write to transfer data and client side receive data in LWS_CALLBACK_RECEIVE_CLIENT_HTTP_READ. But after transferring 1GB, client receive data with 0 length.

**Comment by lws-team** [comment]
What did you have to change for atoll()?  Appveyor was able to build it okay as it is.

If size_t is 32 bits on that platform it's going to fail... it's not a 64-bit platform if it's actually built for win32 and the biggest thing it can count is 4G.

Can you change to the following in lib/libwebsockets.h line 697

```
typedef unsigned long long lws_filepos_t;
typedef long long lws_fileofs_t;
```

that might help.

**Comment by WebsocketUser** [comment]
#define atoll _atoi64
lws_filepos and lws_fileofs_t I already update to unsigned long long and long long.But still not work.

**Comment by lws-team** [comment]
Win32 stat() that we use only supports 32-bit file lengths.  You'll need to use one of the insane number of variants on offer here (stat64? stat32i64?)

https://msdn.microsoft.com/en-us/library/14h5k7ff.aspx

that actually supports 64-bit file lengths.  The only place seems to be server.c line 404.

**Comment by WebsocketUser** [comment]
I modify some places. The issue had been resolved.
Thanks.

**Comment by lws-team** [comment]
Can you send a patch please?

Just the result of `git diff` will do.

**Comment by WebsocketUser** [comment]
client.c Line787
atoi(lws_hdr_simple_ptr(wsi,... ->atoll(lws_hdr_simple_ptr(wsi,...

libwebsockets.h Line696->698
typedef size_t lws_filepos_t; ->typedef unsigned long long lws_filepos_t;
typedef ssize_t lws_fileofs_t;->typedef long long lws_fileofs_t;
typedef uint32_t lws_fop_flags_t;->typedef uint64_t lws_fop_flags_t;

lws-plat-win.c Line 598, 619
                                                                        LARGE_INTEGER llFileSize = {0};

fop_fd->len = GetFileSize(ret, NULL); ->	if(GetFileSizeEx(ret, &llFileSize))
	                                                                {
		                                                             fop_fd->len = llFileSize.QuadPart;
	                                                                }

output.c Line 516,517
lwsl_info("%s: content_remain = %lu\n"...    ->lwsl_info("%s: content_remain = %llu\n",...
(unsigned long)wsi->u.http.content_remain);  ->(unsigned long long)wsi->u.http.content_remain);

private-libwebsockets.h Line 137-139
#ifndef atoll
#define atoll _atoi64
#endif

service.c Line 617,700
int rlen, n; ->long long rlen, n;
(int)wsi->u.http.content_remain < *len)->wsi->u.http.content_remain < *len)

**Comment by lws-team** [comment]
Thanks for contributing.

I pushed a version of these changes with extra checks in cmake and some more warning removals... it also addresses the win32 32-bit stat() length problem for server side.

Please let me know if I broke anything, otherwise it should support 64-bit file lengths out of the box now.
